# COMMON ENVIRONMENT VARIABLES
## THIS VARIABLES WILL BE USED FOR SCRIPT CONTROL
# >>>----------------------------------------------------
PILS_DEPLOY_DIR=${HOME}/Documents/A4VAI-PILS
# FOR PF-CA INTEGRATION TEST
GAZEBO_POSE="-x -27.50 -y 27.50 -z 0.00 -Y -0.785398"
# FOR PP-PF INTEGRATION TEST
#GAZEBO_POSE="-x -180.6640 -y 170.8984 -z 10.0 -Y -0.785398"
PILS_NETWORK_NAME=pils_network
PILS_NETWORK_SUBNET=172.70.0.0/16

PILS_ROS_DOMAIN_ID="" # IF NOT SET, THIS WILL BE RANDOMLY GENERATED
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


# DEPENDENT ENVIRONMENT VARIABLES
## DO NOT MODIFY THESE VARIABLES UNLESS YOU KNOW WHAT YOU ARE DOING
# >>>----------------------------------------------------
PILS_ENV_DIR=${PILS_DEPLOY_DIR}/envs

PX4_WORKSPACE=${PILS_DEPLOY_DIR}/PX4-Autopilot
GAZEBO_CLASSIC_WORKSPACE=${PILS_DEPLOY_DIR}/Gazebo-Classic
AIRSIM_WORKSPACE=${PILS_DEPLOY_DIR}/AirSim
ROS2_WORKSPACE=${PILS_DEPLOY_DIR}/ROS2
QGC_WORKSPACE=${PILS_DEPLOY_DIR}/QGroundControl
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<